services:
  - type: web
    name: ai-tool-frontend
    env: static
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html